layout_spectrum: 0.9910395
color:
  saturation: 1
  brandStrength: 0.07885305
  lightness: 0.9336917
  brandColors:
    - '#0C0C0C'
    - '#808080'
    - '#5C5C5C'
    - '#FBFBFB'
  rhythmicContrast: 0.2775588
typography_spectrum: 0
name: evmeerkat.com
